# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='educational_focus',
        ),
        migrations.RemoveField(
            model_name='about',
            name='zipcode',
        ),
    ]
