# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160229_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='why_quote',
            field=models.CharField(max_length=100),
        ),
    ]
