# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='lyric',
            field=models.ManyToManyField(blank=True, to='lyrics.Lyric'),
        ),
    ]
