# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_auto_20160303_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='mood',
            name='lyric',
        ),
        migrations.AddField(
            model_name='lyric',
            name='mood',
            field=models.ManyToManyField(blank=True, to='lyrics.Mood'),
        ),
        migrations.AddField(
            model_name='lyric',
            name='genre',
            field=models.ManyToManyField(blank=True, to='lyrics.Genre'),
        ),
    ]
