# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0003_auto_20160303_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='lyric',
            old_name='mood',
            new_name='moods',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
