# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0004_auto_20160303_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='moods',
        ),
        migrations.AddField(
            model_name='genre',
            name='lyrics',
            field=models.ManyToManyField(blank=True, to='lyrics.Lyric'),
        ),
        migrations.AddField(
            model_name='mood',
            name='lyrics',
            field=models.ManyToManyField(blank=True, to='lyrics.Lyric'),
        ),
    ]
